const ayarlar = {
  TOKEN: ""
  owner: "626465919291621377",
  prefix: ".",

};

module.exports = ayarlar;

//BOT TOKENINIZI EGER BOT GLITCHDE KALACAK
//ISE .ENV DOSYASINA
//EGER VDS YE KURACAK ISENIZ YUKARIYA 1. SATIRA YAZIN4

